zuul:
  routes:
    get:
      path: /get/**
      url: http://httpbin.org/get
    links:
      path: /links/**
      url: http://httpbin.org/links
    images:
      path: /image/**
      url: http://httpbin.org/image
    user-agent:
      path: /user-agent/**
      url: http://httpbin.org/user-agent

eureka:
  client:
    enabled: false
